### ISSUE TITLE
-f option does not work on windows 10

### ISSUE THREAD

**Issue by jovajiv** [Battleman/zoomdl#35]
**Prerequisite**

- [x] I have updated to the latest version,
- [] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened and closed issues for a duplicate,

**Describe the bug**

I've tried to use the -f option to rename the output file so that it would not overwrite the previous download.
it does not work.

**To Reproduce**

1. Go to 'zoomdl.exe -u url-f filename'
2. output is always the default output

**Expected behavior**

CMD OUTPUT :
C:\Users\jovaj\Downloads\zoom>zoomdl.exe -u https://us02web.zoom.us/rec/play/NNgbNCNR6FyNJL649qhRAKqRrLP_A7skzFl0b-P2duxpOXFaUza9XM9BR6EkREvI-R4HbHKl4Fac-zju.cPzNcQovOhFcaE9F?startTime=1605103851000&_x_zm_rtaid=xiTTcvpVT7OfuUf1YDLjyg.1608486501273.f8995b640a3c38dea7752a1edd446d57&_x_zm_rhtaid=682 -f file
Downloading 'C:\Users\jovaj\Downloads\zoom\יסודות_בגנומיקה_חישובית_-_שעור.mp4'...

**Screenshots**

**URL (opt)**

https://...

**Logs**

```
<LOGS>
```
**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Python Version: [e.g. 3.8.7]

**Additional context (opt)**

**Comment by metal450** [comment]
Doesn't only apply to Windows - the issue is the same on Linux.  Neither -f nor -fname seem to do anything.

(This makes it impossible to download some vidoes that have invalid characters in their filenames - those files fail to save, and cannot be given a name specification to avoid the issue).

**Comment by Battleman** [comment]
That's interesting. I can't seem to reproduce the problem. Works for me on Windows 10 and on Debian 10, both python 3.7.6.
Can you launch the command with max verbosity (`-v 0`) and report the output (as well as your python version, with `python -V`) ?

**Comment by metal450** [comment]
python -V is 2.7.18
python3 -V is 3.8.5

If I run zoomdl on an ntfs partition from Linux (aka where colons aren't supported in filenames, but without -f, just only specifying url), it errors out:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/zoomdl/__main__.py", line 20, in <module>
  File "/usr/bin/zoomdl/zoom_dl/__init__.py", line 18, in main
  File "/usr/bin/zoomdl/zoom_dl/zoomdl.py", line 192, in download
  File "/usr/bin/zoomdl/zoom_dl/zoomdl.py", line 121, in download_vid
OSError: [Errno 22] Invalid argument: '/media/metal450/SSD-Data/Cloud/Desktop/NoSync/zoomdl/Day_1:_Investing_w_Stock_Options.mp4'
```

If I do it on a Linux partition, it works (but per this issue, ignores the output filename). Here's the output o running with -f and -v 0 on a btrfs partition:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/zoomdl/__main__.py", line 20, in <module>
  File "/usr/bin/zoomdl/zoom_dl/__init__.py", line 18, in main
  File "/usr/bin/zoomdl/zoom_dl/zoomdl.py", line 192, in download
  File "/usr/bin/zoomdl/zoom_dl/zoomdl.py", line 113, in download_vid
  File "/usr/bin/zoomdl/zoom_dl/zoomdl.py", line 241, in get_filepath
FileNotFoundError: [Errno 2] No such file or directory
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 76, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/bin/zoomdl/__main__.py", line 20, in <module>
  File "/usr/bin/zoomdl/zoom_dl/__init__.py", line 18, in main
  File "/usr/bin/zoomdl/zoom_dl/zoomdl.py", line 192, in download
  File "/usr/bin/zoomdl/zoom_dl/zoomdl.py", line 113, in download_vid
  File "/usr/bin/zoomdl/zoom_dl/zoomdl.py", line 241, in get_filepath
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by Battleman** [comment]
Yesterday I pushed yesterday and just released v20210101, that fixes the issue of colons (as per #36). Hopefully this fixes the first problem. As I use Windows in a VM on Linux, the issues with NTFS don't appear to me. 
As per the issue on Linux, I'm not sure? It seems `os.getcwd()` throws the error, [line 241](https://github.com/Battleman/zoomdl/blob/8a9287486c57925265bff9da66ef370aab7348fb/zoom_dl/zoomdl.py#L241). I find no report of `getcwd` not playing nice with btrfs. What is the _exact_ command you launch?

**Comment by Battleman** [comment]
@jovajiv for your problem, my guess is that you didn't put quotes around the url (see [this](https://github.com/Battleman/zoomdl/tree/v20210101#about-quotes-important)). 
Thus when you type 
```
zoomdl.exe -u https://us02web.zoom.us/rec/play/NNgbNCNR6FyNJL649qhRAKqRrLP_A7skzFl0b-P2duxpOXFaUza9XM9BR6EkREvI-R4HbHKl4Fac-zju.cPzNcQovOhFcaE9F?startTime=1605103851000&_x_zm_rtaid=xiTTcvpVT7OfuUf1YDLjyg.1608486501273.f8995b640a3c38dea7752a1edd446d57&_x_zm_rhtaid=682 -f myfile
```
The terminal (cmd, powershell, bash...) sees this
```
https://us02web.zoom.us/rec/play/NNgbNCNR6FyNJL649qhRAKqRrLP_A7skzFl0b-P2duxpOXFaUza9XM9BR6EkREvI-R4HbHKl4Fac-zju.cPzNcQovOhFcaE9F?startTime=1605103851000
&
_x_zm_rtaid=xiTTcvpVT7OfuUf1YDLjyg.1608486501273.f8995b640a3c38dea7752a1edd446d57
&
_x_zm_rhtaid=682 -f myfile
```
and tries to do 3 commands. Hence, the -f isn't attached to the original command, and zoomdl doesn't see this.

**Comment by metal450** [comment]
> Yesterday I pushed yesterday and just released v20210101, that fixes the issue of colons (as per #36). Hopefully this fixes the first problem.

Nope - still happens w/ current master.

> As per the issue on Linux ... What is the _exact_ command you launch?

It's a semi-private zoom link so I can't share the actual url, but just `zoomld -u "the_url" -f file.mp4`

**Comment by Battleman** [comment]
I don't see anything that would fail it. All my tests show it should work. It looks like the recording doesn't have a name at all? If still available, could you share a link that fails at zoomdl[at]cloux.dev ? Truly 0 interest in the content of the recording, but if I can reproduce it I can debug it, otherwise it's kinda hard.

**Comment by metal450** [comment]
Thanks for the reply.  Totally fair enough - unfortunately I just can't (I actually have a signed NDA about the contents of the meeting, so if I were to send it anywhere, I could theoretically get in trouble).  In any case, I was able to get it downloaded by just doing so to a non-ntfs partition, so I guess it's fine for now, & I can report back in the event that I can reproduce it again on a sharable link.  Thanks again for trying, tho :)

**Comment by jacobrosenfeld** [comment]
I think I found that you need the quotes around the filename argument as well 
so -u "zoom.us/qwerty" -f "filename123"
That's how I enter the arguments on my Macbook Pro and it works great!

**Comment by Battleman** [comment]
No news about that, so it can't be reproduced for how. Closing until/if a reproducible case arises.
