### ISSUE TITLE
Support for zoomgov links?

### ISSUE THREAD

**Issue by jpelgrift** [Battleman/zoomdl#44]
**Prerequisite**

- [] I am asking a question, and not reporting a bug or a feature request
- [x] I have searched the opened and closed issues for a duplicate,

**Question**
Is it possible to get support for zoomgov links as well? I got it to work by just replacing every occurrence of 'zoom.us' in the code with 'zoomgov.com', but it'd be great if it worked natively for both. Everything else about the url is the same as zoom.us links (https://\<domain>.zoomgov.com/rec/play/\<id>).

**Comment by Battleman** [comment]
That sounds doable. I'll add more generic calls to zoom.us, let me know if you encounter with the next version

**Comment by Battleman** [comment]
This should be fixed in 2021.03.27. If this doesn't work, feel free to reopen and let me know.

**Comment by jpelgrift** [comment]
Thanks for the very fast response!

I see the change you made, but this unfortunately still does not work. The zoomgov links are at zoomgov**.com** instead of zoomgov.us (different TLD) so with '.us' hardcoded it still isn't working.

**Comment by Battleman** [comment]
Ah, didn't notice that difference, my bad. Fair enough, I'll adapt that tomorrow.

**Comment by Battleman** [comment]
Voila, should be fixed in 2021.03.28
